name: GPT Developer

on:
  issues:
    types:
      - labeled

jobs:
  update-code-on-issue:
    if: github.event.label.name == 'to-do'
    name: Update the code according to issue text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update code
        uses: skaramicke/gpt-developer@a2
        id: gpt
        with:
          openai_api_key: ${{ secrets.OPENAI_API_SECRET }}
          issue_number: ${{ github.event.issue.number }}
          issue_text: "${{ github.event.issue.title}}, ${{ github.event.issue.body }}"
          path: ${{ github.workspace }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.gpt.outputs.commit_message }} - gpt-developer
