name: GPT Developer

on:
  issues:
    types:
      - labeled

env:
  CODE_PATH: code

jobs:
  update-code-on-issue:
    if: github.event.label.name == 'to-do'
    name: Update the code according to issue text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.CODE_PATH }}

      - name: Update code
        uses: skaramicke/gpt-developer@a2
        id: gpt
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          issue_number: ${{ github.event.issue.number }}
          issue_text: "${{ github.event.issue.title}}, ${{ github.event.issue.body }}"
          path: ${{ env.CODE_PATH }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          commit_message: ${{ steps.gpt.outputs.commit_message }}
          add: ${{ env.CODE_PATH }}
