name: GPT Developer

on:
  issues:
    types:
      - labeled

env:
  CODE_PATH: code

jobs:
  update-code-on-issue:
    if: github.event.label.name == 'to-do'
    name: Update the code according to issue text
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "I'm working on it! - GPT Developer"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.CODE_PATH }}

      - name: Update code
        uses: skaramicke/gpt-developer@a2
        id: gpt
        with:
          openai_api_key: ${{ secrets.OPENAI_API_SECRET }}
          issue_number: ${{ github.event.issue.number }}
          issue_text: "${{ github.event.issue.title}}, ${{ github.event.issue.body }}"
          path: ${{ env.CODE_PATH }}

      - name: Add exit message to issue comments
        if: steps.gpt.outputs.exit_message != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.gpt.outputs.exit_message }}

      - name: Commit changes
        if: steps.gpt.outputs.commit_message != ''
        uses: EndBug/add-and-commit@v7
        with:
          commit_message: ${{ steps.gpt.outputs.commit_message }}
          add: ${{ env.CODE_PATH }}

      - name: Add commit message to issue comments
        if: steps.gpt.outputs.commit_message != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.gpt.outputs.commit_message }} - commit by GPT Developer
